### ISSUE TITLE
async void

### ISSUE THREAD

**Issue by MrMuMu** [davidfowl/AspNetCoreDiagnosticScenarios#15]
I have to disagree on your statement:

> Use of async void in ASP.NET Core applications is ALWAYS bad. Avoid it, never do it.

I know what the motivation is but the expression is wrong. async void has use case(s?) and should be used only if needed be. Such, maybe only, example is async event handler.

**Comment by MrMuMu** [comment]
There may be cases where the result of the async action has to be awaited, but anyways you're welcome.

**Comment by davidfowl** [comment]
What do you mean? If you’re async void, who is awaiting?

**Comment by MrMuMu** [comment]
I was trying to say this;

    something.SomeEventHandler += async (sender, e) =>
    {
        someimportantvalue = await AsyncThing();

        AsyncThing2(someimportantvalue)
    }

and if we need to handle exceptions we can always use try catch

    something.SomeEventHandler += async (sender, e) =>
    {
        try
        {
             someimportantvalue = await AsyncThing();

             await AsyncThing2(someimportantvalue)
        }
        catch (Exception ex)
        {
             //handle as you wish
        }
    }

**Comment by nopara73** [comment]
But, without async void you cannot unsubscribe and you'll have a memory leak?

**Comment by davidfowl** [comment]
@MrMuMu just write all of that code in the asynchronous method. Not sure I understand the problem.

@nopara73 I don’t understand the concern. What does async void have to do with unsubscribing?

**Comment by nopara73** [comment]
```cs
something.SomeEventHandler += (sender, e) =>
{
   // Cannot unsubscribe -> Memory leak.
};
```

```cs
something.SomeEventHandler += HandleEventAsync;
...
async void HandleEventAsync(object sender, EventArgs e)
{
   await DoSomethingAsync();
}
...
something.SomeEventHandler -= HandleEventAsync; // Unsubscribing -> No Memory Leak.
```

**Comment by davidfowl** [comment]
Ok that’s unrelated to the other discussed problems though..

**Comment by davidfowl** [comment]
Closing this out.

**Comment by davidfowl** [comment]
I should clarify, windows forms and WPF have SynchrozationContext implementations that will handle unhandled exceptions. That is *NOT* the case in ASP.NET Core. The process will crash if your async void handlers throw errors. They are generally recommended against everywhere on the server side. You can use them in winforms/wpf/xamarin applications (unfortunately 😄).

**Comment by MrMuMu** [comment]
Sorry for the late answer, I see my mistake in the example I will try to give more detailed one;

    SomeThing st = new Something();
    st.SomeEventHandler += async (sender, e) =>
    {
        try
        {
              ((SomeThing)st).someValue = await AsyncThing();
        }
        catch (Exception ex)
        {
              ((SomeThing)st).someValue = //whatever you wish that makes you understand that the event has failed
        }
    };

If you need the `someValue` available after the event you can not use fire-and-forget, so you need to `await` the `AsyncThing()` to get the result.

Hope this helps.

**Comment by davidfowl** [comment]
> If you need the someValue available after the event you can not use fire-and-forget, so you need to await the AsyncThing() to get the result.

Are you assuming that the thing calling the event handler is waiting for your async void method to complete? Because *nothing* is waiting on your async void method.

**Comment by MrMuMu** [comment]
> Are you assuming that the thing calling the event handler is waiting for your async void method to complete? Because nothing is waiting on your async void method.

Oh! I don't really know how I missed that. You are right my mistake,, I am very sorry for wasting your time. Thank you for the explanation.
