### ISSUE TITLE
async void example won't compile

### ISSUE THREAD

**Issue by jchannon** [davidfowl/AspNetCoreDiagnosticScenarios#21]
In https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md under "Async Void" the example code snippet won't compile anyway

**Comment by davidfowl** [comment]
Not sure what you mean. Are you talking about missing functions? Or something else?

**Comment by jchannon** [comment]
In the example:

```
        public async Task BackgroundOperationAsync()
        {
            var result = await CallDependencyAsync();
            return result + 1;
        }
```

This won't compile
