### ISSUE TITLE
Add: Best practice when you want to use async when disposing an IDisposable.

### ISSUE THREAD

**Issue by nopara73** [davidfowl/AspNetCoreDiagnosticScenarios#22]
I'm sorry, I don't have the answer, I'd just like to note that this is a common problem.

**Comment by davidfowl** [comment]
Great question! `IAsyncDisposable` is coming https://github.com/dotnet/corefx/issues/32640 but there's no good way of solving this now. I usually expose a DisposeAsync() method, instead of implementing IDisposable but then it means that callers can't do using statements.

**Comment by nopara73** [comment]
That'll be wonderful. Should I close this issue or you'd prefer me to keep it alive?

**Comment by davidfowl** [comment]
Closing it is fine 😄
