### ISSUE TITLE
When buffering, still check if response HasStarted

### ISSUE THREAD

**Issue by Tratcher** [davidfowl/AspNetCoreDiagnosticScenarios#23]
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blame/d319a43874ca5d25c5e12dcbba8f8bc71a81e102/AspNetCoreGuidance.md#L187-L200

When buffering you should still check Response.HasStarted before setting response headers (like the prior [example](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blame/d319a43874ca5d25c5e12dcbba8f8bc71a81e102/AspNetCoreGuidance.md#L179-L183). Buffers can be Flushed to start the response early.

**Comment by davidfowl** [comment]
@Tratcher feel free to send a PR to update the document.

**Comment by davidfowl** [comment]
Fixed, removed the buffering example and added an OnStarting example.

**Comment by doggy8088** [comment]
@davidfowl Can I read the bufferred stream in the next middleware?

**Comment by davidfowl** [comment]
Sure. If it rewound.

**Comment by doggy8088** [comment]
@davidfowl For example, I have two middlewares.  

```cs
app.UseResponseBuffering();
app.UseMiddleware<Middleware1>();
app.UseMiddleware<Middleware2>();
```

I have something need to write in the `Middleware2`.  I want to read the whole buffer in the `Middleware1`.  How can I achieve this?  The `ResponseBuffering`'s bufferred stream is write only.  I can't read it. Can you give me a hint how to do this?

**Comment by doggy8088** [comment]
@davidfowl I setup a simple repo to describe my question.  Would you take a look?
https://github.com/doggy8088/buffer-middleware-test/blob/master/Startup.cs#L30-L31

**Comment by davidfowl** [comment]
You can't read the response body, the stream is write only. If you want to read the output then you should assign a `MemoryStream`.

**Comment by doggy8088** [comment]
@davidfowl Where is the `MemoryStream` should I assign to?

**Comment by doggy8088** [comment]
@davidfowl I made it. [Here is my code.](https://github.com/doggy8088/buffer-middleware-test/blob/c4b0b1dcc6f7568a79a638e9879d92f67b911cc9/Startup.cs#L29-L55)  Is my implementation okay? 😃

**Comment by Tratcher** [comment]
Stream _original and MemoryStream _buffered should not be class variables, they should be local variables inside Use. Otherwise you'll get cross contamination between requests. Is that why you had the null check on line 41?

Side notes:
- Be careful with WriteLineAsync, you're adding an extra new line that the original response did not have. That should be WriteAsync.
- You don't need that initial HasStarted check, you should never be called for a response that has already started.
