### ISSUE TITLE
Link to CoreFx issue for async WindowsIdentity.RunImpersonated

### ISSUE THREAD

**Issue by Tratcher** [davidfowl/AspNetCoreDiagnosticScenarios#24]
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/d319a43874ca5d25c5e12dcbba8f8bc71a81e102/AsyncGuidance.md#windowsidentityrunimpersonated

https://github.com/dotnet/corefx/issues/24977

**Comment by davidfowl** [comment]
This is fixed now
