### ISSUE TITLE
Is this typo? BigContentJsonManualUBuffered on BigJsonOutputController

### ISSUE THREAD

**Issue by fish0185** [davidfowl/AspNetCoreDiagnosticScenarios#34]
https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/01d7bf5cd0641b53b77cce14540ef9ca314e9177/Scenarios/Controllers/BigJsonOutputController.cs#L47

**Comment by davidfowl** [comment]
Yep

**Comment by davidfowl** [comment]
Fixed! Thanks!
