### ISSUE TITLE
Include Guidance.md in Readme.md

### ISSUE THREAD

**Issue by agarcialeon** [davidfowl/AspNetCoreDiagnosticScenarios#45]
Could be possible to include the links in Guidance.md file into the README.md file so when visiting the repository navigation to each section becomes easier?

**Comment by WiredUK** [comment]
Why don't you add it yourself in a pull request? I'm sure David would appreciate it.

**Comment by agarcialeon** [comment]
Yeah, of course! I didn't know the intention about how David would like to organize the repository. It was just a suggestion. Thanks for the advice.

**Comment by davidfowl** [comment]
Thanks!
