### ISSUE TITLE
Analyzer for “Prefer async/await over directly returning Task”?

### ISSUE THREAD

**Issue by atifaziz** [davidfowl/AspNetCoreDiagnosticScenarios#67]
Anyone aware of a Roslyn-based analyzer for the guidance “[Prefer async/await over directly returning Task](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/519ef7d231c01116f02bc04354816a735f2a36b6/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task)”?

---
/cc @p-schuler

**Comment by gfoidl** [comment]
The closet I know is [RCS1229: Use async/await when necessary](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1229.md) from Roslynator.

**Comment by atifaziz** [comment]
Thanks, @gfoidl! That seems to come pretty and will take it for a spin. On first looks, it caters for `using` statement/declaration mostly but might need extending to the general try-catch/-finally case that seems to be missing.
