### ISSUE TITLE
Typo in HttpClientGuidance.md

### ISSUE THREAD

**Issue by eisenpony** [davidfowl/AspNetCoreDiagnosticScenarios#74]
The note about WebClient contains some contradictory advice.

> WebClient is considered a legacy .NET API at this point and has been completely superseded by HttpClient. No new code should be written with HttpClient.

Seems to suggest HttpClient should both:
1. be used instead of WebClient
2. never be used

**Comment by udlose** [comment]
there is already a PR for this typo.  Just hasn't been merged yet - https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/pull/71

**Comment by eisenpony** [comment]
Thanks. Still learning github 😅
